<?php

/**
 * PackageRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Redracer
 * @subpackage Database
 * @author     Benjamin Börngen-Schmidt <benjamin@boerngen-schmidt.de>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class PackageRelease extends BaseRelease
{

}