---
options:
  collate: utf8_unicode_ci
  charset: utf8
attributes:
  export: all

Project:
  package: Project
  tableName: project
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    name:
      type: string(50)
      notnull: true
    short_description:
      type: string(200)
      notnull: true
    long_description:
      type: string(10000)
      notnull: true
    scm_url:
      type: string(200)
      notnull: false
    bug_tracker_url:
      type: string(200)
      notnull: false
    date:
      type: integer
      notnull: true
    owner:
      type: integer
      notnull: true
  relations:
    Owner:
      local: owner
      type: one
      class: Developer
      foreignAlias: OwnedProjects
      foreignType: many
      foreign: id
    Developers:
      class: Developer
      local: project
      type: many
      foreign: developer
      foreignAlias: DevelopingProjects
      foreignType: many
      refClass: ProjectDeveloper
    Tags:
      local: project
      foreign: tag
      type: many
      foreignType: many
      class: Tag
      refClass: ProjectsTags
      foreignAlias: Projects

Release:
  package: Project
  tableName: release
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    description:
      type: string(1000)
      notnull: false
    date:
      type: integer
      notnull: true
    project:
      type: integer
      notnull: true
    likes:
      type: integer
      notnull: true
    dislikes:
      type: integer
      notnull: true
  relations:
    Project:
      local: project
      foreign: id
      type: one
      foreignAlias: Releases
      

File:
  package: Project
  tableName: file
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    description:
      type: string(200)
      notnull: false
    binary_path:
      type: string(200)
      notnull: true
    size:
      type: integer
      notnull: true
    release:
      type: integer
      notnull: true
  relations:
    Release:
      local: release
      foreign: id
      type: one
      foreignAlias: Files

Tag:
  package: Project
  tableName: tag
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    name:
      type: string(20)
      notnull: true
    description:
      type: string(200)
      notnull: true

ProjectDeveloper:
  package: Project
  tableName: project_developer
  columns:
    project:
      type: integer
      primary: true
    developer:
      type: integer
      primary: true
    approved:
      type: boolean
      notnull: true
      default: false

Developer:
  package: Developer
  tableName: developer
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    name:
      type: string(50)
      notnull: true
    email:
      type: string(50)
      notnull: true
    website_url:
      type: string(200)
      notnull: false
    avatar_url:
      type: string(200)
      notnull: false
    password:
      type: string(128)
      notnull: true
    salt:
      type: string(40)
      notnull: true
    is_team_member:
      type: boolean
      notnull: true
      default: false

Comment:
  package: Developer
  tableName: comment
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    text:
      type: string(1000)
      notnull: true
    date:
      type: integer
      notnull: true
    release:
      type: integer
      notnull: true
  relations:
    Release:
      local: release
      foreign: id
      type: one

ProjectsTags:
  package: Project
  tableName: project_tag
  columns:
    project:
      type: integer
      notnull: true
      primary: true
    tag:
      type: integer
      notnull: true
      primary: true

RatingsLog:
  package: Log
  tableName: ratings_log
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    ip_address:
      type: string(15)
      notnull: true
    session_id:
      type: string(100)
      notnull: true
    date:
      type: integer
      notnull: true
    release:
      type: integer
      notnull: true
    liked:
      type: boolean
      notnull: true
  relations:
    Release:
      local: release
      type: one
      foreign: id
      foreignAlias: RatingLogs
      foreignType: many